services:
  webclient:
    container_name: mmo_webclient
    build:
      context: .
      dockerfile: ./webclient/Dockerfile
    ports:
      - "3000:3000"
  game-server:
    container_name: mmo_game_server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_URL=jdbc:postgresql://mmo_postgres:5432/game
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9000:9000"
  postgres:
    container_name: mmo_postgres
    image: postgres
    environment:
      POSTGRES_DB: "game"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d game"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
