include:
  - ../database/docker-compose.yaml
services:
  game-server:
    container_name: mmo_game_server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_URL=jdbc:postgresql://mmo_postgres:5432/game
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "9000:9000"